export const bios = [
  "Explorando o mundo bit por bit.",
  "Apaixonado por tecnologia e café.",
  "Escrevendo código e criando sonhos.",
  "Navegando no universo da programação.",
  "Amando a vida e a programação!",
  "Transformando café em código.",
  "Vivendo, aprendendo e codificando.",
  "Construindo pontes entre humanos e máquinas.",
  "Aventureiro digital em busca de inovação.",
  "Amante de algoritmos e aventuras.",
  "Devorando livros e expandindo horizontes.",
  "Maratonando séries e descobrindo novos mundos.",
  "Apaixonado por filmes e suas narrativas.",
  "Explorando novos destinos com amigos.",
  "Saboreando cada página de um bom livro.",
  "Viciado em séries e suas reviravoltas.",
  "Colecionando momentos com os amigos.",
  "Explorando o mundo através das telas.",
  "Amante de bons livros e boas conversas.",
  "Apreciando filmes e criando memórias.",
];