export const initialTweets = [
  {
    id: "1a23bc45-678d-9e01f-gh23i4jkl567",
    userAvatar: "https://source.unsplash.com/random/?woman?teenagers",
    userName: "Alice Johnson",
    userLogin: "alice_j",
    content: "Que tal estudar programação?",
    comments: 15,
    retweets: 3,
    likes: 789,
    views: 4567,
  },
  {
    id: "13m56no78-901p-234q-567r8s9012",
    userAvatar: "https://source.unsplash.com/random/?woman?9",
    userName: "Mariana Lima",
    userLogin: "marianal",
    content: "Amo meu novo hobby de pintura! 🎨 #Pintura",
    comments: 11,
    retweets: 2,
    likes: 757,
    imageUrl: "https://source.unsplash.com/random/?sketch",
    views: 4370,
  },
  {
    id: "4d56ef78-901g-234h-j56k7lmn890",
    userAvatar: "https://source.unsplash.com/random/?man?324",
    userName: "Carlos Mendes",
    userLogin: "carlosmendes88",
    content: "Assistindo minha nova série favorita!",
    comments: 8,
    retweets: 1,
    likes: 432,
    views: 2109,
  },
  {
    id: "2b34cd56-789e-0f12g-hi34j5klm678",
    userAvatar: "https://source.unsplash.com/random/?person?men",
    userName: "John Smith",
    userLogin: "johnsmith123",
    content: "Compartilhando uma receita deliciosa de bolo para vocês 🍫🍰",
    comments: 25,
    retweets: 7,
    likes: 1564,
    views: 8901,
    imageUrl: "https://source.unsplash.com/random/?cakes",
  },
  {
    id: "3c45de67-890f-123g-i45j6klm789",
    userAvatar: "https://source.unsplash.com/random/?woman/236",
    userName: "Maria Silva",
    userLogin: "mariasilva",
    content: "Nada melhor do que ler um livro 📚🌙 #Livros",
    comments: 12,
    retweets: 2,
    likes: 678,
    imageUrl: "https://source.unsplash.com/random/?reading",
    views: 3456,
  },
  {
    id: "5e67fg89-012h-345i-k67l8mno901",
    userAvatar: "https://source.unsplash.com/random/?woman/5",
    userName: "Lúcia Oliveira",
    userLogin: "lucia_oliveira",
    content: "Admire a beleza da natureza. 🌿",
    comments: 20,
    retweets: 5,
    likes: 1283,
    views: 6852,
  },
  {
    id: "6f78gh90-123i-456j-l78m9nop012",
    userAvatar: "https://source.unsplash.com/random/?men/3",
    userName: "Pedro Alves",
    userLogin: "pedroalves",
    content: "Noite agradável com amigos!pura diversão e vários drink's",
    comments: 30,
    retweets: 9,
    likes: 2124,
    imageUrl: "https://source.unsplash.com/random/?drinks?champanhe",
    views: 9876,
  },
  {
    id: "7g89hi01-234j-567k-890l1mno23p",
    userAvatar: "https://source.unsplash.com/random/?woman?3",
    userName: "Laura Santos",
    userLogin: "laura_s",
    content: "Apreciando um café quentinho neste dia frio. ☕❄️ ",
    comments: 18,
    retweets: 4,
    likes: 635,
    views: 5432,
  },
  {
    id: "8h90ij12-345k-678l-901m2n345o",
    userAvatar: "https://source.unsplash.com/random/?men?8",
    userName: "Ricardo Pereira",
    userLogin: "ricardop",
    content:
      "Participando de uma palestra incrível hoje! varias informações importantes",
    comments: 22,
    retweets: 6,
    likes: 1542,
    views: 7654,
  },
  {
    id: "9i01jk23-456l-789m-012n3o4567",
    userAvatar: "https://source.unsplash.com/random/?woman?763",
    userName: "Isabel Fernandes",
    userLogin: "isabelf",
    content: "Finalmente de férias! partiu viajar",
    comments: 14,
    retweets: 2,
    likes: 852,
    views: 4321,
  },
  {
    id: "10j23kl45-678m-901n-234o5p6789",
    userAvatar: "https://source.unsplash.com/random/?children/3",
    userName: "André Costa",
    userLogin: "andrec",
    content: "Explorando novos lugares hoje! 🌍 #Aventura #Viagem",
    comments: 16,
    retweets: 3,
    likes: 1108,
    imageUrl: "https://source.unsplash.com/random/?explore?travel?adventure",
    views: 5927,
  },
  {
    id: "11k34lm56-789n-012o-345p6q7890",
    userAvatar: "https://source.unsplash.com/random/?woman/39",
    userName: "Eva Oliveira",
    userLogin: "eva_o",
    content: "Dia produtivo de trabalho! 💼 #Trabalho #Produtividade",
    comments: 10,
    retweets: 1,
    likes: 638,
    views: 3001,
  },
  {
    id: "12l45mn67-890o-123p-456q7r8901",
    userAvatar: "https://source.unsplash.com/random/?woman/967",
    userName: "Paulo Ramos",
    userLogin: "paulor",
    content: "Noite tranquila assistindo a um filme. 🍿",
    comments: 21,
    retweets: 5,
    likes: 1303,
    imageUrl: "https://source.unsplash.com/random/?cinema",
    views: 6543,
  },
  {
    id: "14n67op89-012q-345r-678s9t0123",
    userAvatar: "https://source.unsplash.com/random/?men?71",
    userName: "Daniel Sousa",
    userLogin: "daniels",
    content: "Aprendendo algo novo a cada dia. #Crescimento",
    comments: 19,
    retweets: 4,
    likes: 906,
    views: 5076,
  },
  {
    id: "15o78pq90-123r-456s-789t0u1234",
    userAvatar: "https://source.unsplash.com/random/?woman/94",
    userName: "Ana Santos",
    userLogin: "anas",
    content: "Hoje é dia de relaxar e recarregar as energias.",
    comments: 13,
    retweets: 3,
    likes: 1020,
    views: 6035,
  },
];
